### ISSUE TITLE
Support https queries to API endpoints

### ISSUE THREAD

**Issue by wish7code** [GuillaumeAmat/leaflet-overpass-layer#11]
Hey,

currently Overpass queries are sent using unencrypted **http** (see https://github.com/GuillaumeAmat/leaflet-overpass-layer/blob/3b47cc1dfae1e1d9fc3f28561b2219d2a5cda325/src/OverPassLayer.js#L13) instead of **https**.

This will lead to problems, when leaflet-overpass-layer is rolled out to an https hosts. In such situations browser won't allow leaflet-overpass-layer queries to the endpoint due to mix-content policies (e.g. Firefox error: _Loading of mixed active contents "http://overpass-api.de/api/interpreter?data=[out:json];(...);out;" was blocked._) Thus leaflet-overpass-layer won't work on any https site.

Suggestion: change endpoint api to https://overpass-api.de/api ??

Cheers
Toby

**Comment by GuillaumeAmat** [comment]
Hi @wish7code,

Actually, you can already change the requests endpoint. You only have to set the *endPoint* option when creating the layer (see [all the options](https://github.com/GuillaumeAmat/leaflet-overpass-layer#what-are-the-options) in the README).

But the https one might be the default one you're right. I will change that.

Thanks for your feedback!

**Comment by GuillaumeAmat** [comment]
Done!
You can grab the new version whenever you want.

**Comment by wish7code** [comment]
Thanks Guillaume! Works great..
