### ISSUE TITLE
Using with react-leaflet

### ISSUE THREAD

**Issue by jakehm** [GuillaumeAmat/leaflet-overpass-layer#12]
React-leaflet is a react implementation of leaflet. https://github.com/PaulLeCam/react-leaflet

My render function looks like this:
```
  render () {
    return (
      <Map 
        zoom={this.state.zoom}
        center={[this.state.lat, this.state.lng]}
        >
        <TileLayer
          url='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
        />
        <OverpassLayer />
      </Map>
    )
  }
```

OverpassLayer.js
```
import {LayerGroup} from 'react-leaflet'
import L from 'leaflet'
import LeafletOverpassLayer from 'leaflet-overpass-layer'

export default class OverpassLayer extends LayerGroup {
  componentWillReceiveProps(nextProps) {
    const bounds = nextProps.map.getBounds()
    console.log('inside of overpass layer cmpwillrecprops')
    console.log(bounds)
    const opl = new L.LeafletOverpassLayer({
      'query': '[out:json][timeout:25];'
        + '('
        + 'node["amenity"]({{bbox}});'
        + 'way["amenity"]({{bbox}});'
        + 'relation["amenity"]({{bbox}});'
        + ');'
        + 'out body;'
        + '>;'
        + 'out skel qt;'
    })
    nextProps.map.addLayer(opl)
  }
}
```

The error I'm getting is:
`Uncaught (in promise) TypeError: _leaflet2.default.LeafletOverpassLayer is not a constructor`

**Comment by GuillaumeAmat** [comment]
Hi @jakehm,

Try to replace `L.LeafletOverpassLayer` by `L.OverPassLayer`.

**Comment by jakehm** [comment]
Why does that work?  I imported it as LeafletOverpassLayer so shouldn't that be the name of the constructor?

**Comment by GuillaumeAmat** [comment]
Because you have to use the name of the Leaflet plugin, declared here: https://github.com/GuillaumeAmat/leaflet-overpass-layer/blob/develop/src/OverPassLayer.js#L548

Not the import name.

**Comment by jakehm** [comment]
Is that fixable?

**Comment by GuillaumeAmat** [comment]
It's not fixable as it's not a bug ;)
But if you really want to use the import name, use `LeafletOverpassLayer` instead of `L.OverPassLayer`.
