### ISSUE TITLE
Cache requests

### ISSUE THREAD

**Issue by Rudloff** [GuillaumeAmat/leaflet-overpass-layer#15]
Hello,
Do you think it would be possible to add a way to cache requests? (Maybe with localStorage?)
Currently it calls the API again every time we reload the page.

**Comment by GuillaumeAmat** [comment]
Hi!
You're right, I thought about that earlier too. I could be good to propose an option to do that. Enabled by default, with a TTL.

What do you think about that?

```
cacheEnabled: true,
cacheTTL: 1800, // Seconds
```

**Comment by Rudloff** [comment]
Yes, that would be perfect.

**Comment by Rudloff** [comment]
Any news on this? This feature would still be very useful to me :slightly_smiling_face:

**Comment by GuillaumeAmat** [comment]
Unfortunately I don't have much time to do that :(
Could you consider opening a PR?

**Comment by Rudloff** [comment]
I can try to work on a PR that would use localStorage.

**Comment by GuillaumeAmat** [comment]
Great :)

I would suggest to use IndexedDB though. Local storage is limited to 5 MB of data, IndexedDB has a lot more space available.

And [idb](https://www.npmjs.com/package/idb) is both lightweight and useful when considering IndexedDB.

**Comment by Rudloff** [comment]
I agree that localStorage is not the best choice for storing large objects, but I thought you would not want to add dependencies for this (and using IndexedDB directly is kind of tedious).

I a more familiar with [localForage](https://github.com/localForage/localForage) but I will have a look at idb.

**Comment by GuillaumeAmat** [comment]
> I thought you would not want to add dependencies

You're right, but idb is just [1.2 kB](https://bundlephobia.com/result?p=idb@4.0.5) so the add worth it. In comparison, localforage is [8.6 kB](https://bundlephobia.com/result?p=localforage@1.7.3).
