### ISSUE TITLE
Update Leaflet dependency

### ISSUE THREAD

**Issue by Rudloff** [GuillaumeAmat/leaflet-overpass-layer#17]
Similar to #7, leaflet-overpass-layer still requires leaflet ~1.0.1 but we are now at leaflet 1.2.0.
I have tried leaflet-overpass-layer with leaflet 1.2 and did not find any bug.

**Comment by GuillaumeAmat** [comment]
Great to read! Can you consider making a PR? I'm swamped right now...

**Comment by GuillaumeAmat** [comment]
Thank you for the PR, you missed the `package.json` dependency section though ;)
The change is available in the [2.8.0](https://github.com/GuillaumeAmat/leaflet-overpass-layer/releases/tag/2.8.0) version!

**Comment by Rudloff** [comment]
Oh sorry, I totally forgot it's also distributed via npm.
