### ISSUE TITLE
Update Leaflet plugin list

### ISSUE THREAD

**Issue by mmd-osm** [GuillaumeAmat/leaflet-overpass-layer#18]
As the original plugin is no longer maintained and causes performance issues due to a large amount of Overpass API calls, could you maybe update https://github.com/Leaflet/Leaflet/blob/master/docs/plugins.md with a link to your repository?

See https://github.com/Leaflet/Leaflet/pull/3117 for the original pull request.

Leaflet Layer Overpass | Easily include data from the overpass api. | kartenkarsten

**Comment by GuillaumeAmat** [comment]
Done in that PR: https://github.com/Leaflet/Leaflet/pull/5737

**Comment by GuillaumeAmat** [comment]
Thank you for your input by the way ;)
