### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by wish7code** [GuillaumeAmat/leaflet-overpass-layer#2]
Salut Guillaume,

would it be possible to include a working demo (e.g. github.io)?

I was trying to replace kartenkarsten js with your fork, but unfortunately miserably failing, due to missing require.js and clipper.js dependencies.

I've got no clue how to include them :-(

Thanks & cheers
Toby

**Comment by GuillaumeAmat** [comment]
Hi @wish7code!

Thanks for your report, it makes me brave enough to clean a bit the loading environment and to replace Gulp by Webpack :)

Long story short, you can see the requested demo page here: http://guillaumeamat.github.io/leaflet-overpass-layer/demo/index.html

Woohoo!

**Comment by wish7code** [comment]
Thanks Gullaume, that's great news!
I'm looking forward to playing around with it...
