### ISSUE TITLE
180th meridian bug - it's possible to request items outside overpass bounds

### ISSUE THREAD

**Issue by neon-ninja** [GuillaumeAmat/leaflet-overpass-layer#22]
When panning the map past the 180th meridian it's possible to have a bbox outside the allowed -180 - 180 range, causing requests to fail with error 400. This line appears to handle that part - https://github.com/GuillaumeAmat/leaflet-overpass-layer/blob/089b0aa2f6198ec3f75d9cc47cccbe9d5aa6c200/src/OverPassLayer.js#L217

**Comment by GuillaumeAmat** [comment]
Hi @neon-ninja 👋

I don't understand the issue, or at least the solution here. What bbox should be sent to Overpass in your case?

**Comment by neon-ninja** [comment]
Hi,

Try pan the map all the way to the right to view for instance, Samoa. The bbox is then -18.188025228080775,182.91206359863284,-9.724693960406066,193.10188293457034, which fails as overpass expects longitudes within -180 to 180. The longitude should be clamped - ie, subtracted by 360, so 182.91206359863284 should become -177.087936401 and 193.10188293457034 should become -166.898117065. There's a similar issue that occurs when panning all the way to left, where longitudes can go below -180 - 360 should be added in that case (potentially multiple times, to get into the -180 - 180 range

**Comment by neon-ninja** [comment]
Seems related to https://github.com/Leaflet/Leaflet/issues/1885
