### ISSUE TITLE
Runing layer with prepared json?

### ISSUE THREAD

**Issue by pedjas** [GuillaumeAmat/leaflet-overpass-layer#31]
Is it possible to feed OverPassLayer with already prepared json data instead of running query?

**Comment by GuillaumeAmat** [comment]
It is not possible sorry, and for the record, the plugin does not store any loaded data, just the fetched areas bounding boxes.

**Comment by pedjas** [comment]
It would be great to have such option. OverpassTurbo is great service and it would be good to save it's resources by not collecting the same data over and over again.

I do not expect this plugin to do collecting and saving data, but just an option to show json that was prevoiusly got from Overpass Turbo  in other way, maybe by just providing URL to existing json file instead of querying OverPass Turbo.

**Comment by GuillaumeAmat** [comment]
You can already avoid the data fetching by setting the `loadedBounds` option if you want.

Eg:

1. Provide a custom `onSuccess` callback function (see options) to take care of the data handling/display in your own Leaflet layer
2. Fill your Leaflet layer with your local data/markers
3. Set the `loadedBounds` option with the areas that you want to avoid fetching (as they are already displayed by hand)

Hope that makes sense to your use case.
