### ISSUE TITLE
User "onSuccess" for custom Icons etc.?

### ISSUE THREAD

**Issue by Fricke112** [GuillaumeAmat/leaflet-overpass-layer#33]
Hello,
is there a way to use the old feature "callback"? I try to configure the Icons and Popups like in the old version "https://github.com/kartenkarsten/leaflet-layer-overpass" but with your version (because the old always blow the "without the "Too many requests error")?

Greetings

**Comment by GuillaumeAmat** [comment]
Hi, you can use the `onSuccess` callback instead. 

I added several callbacks so I had to rename it to give it more context/sense.
