### ISSUE TITLE
MinZoomIndicator

### ISSUE THREAD

**Issue by Dr-Mx** [GuillaumeAmat/leaflet-overpass-layer#4]
Hi!

Congrats on v2, I'm currently testing it and hope to implement it into my project soon.

I've noticed that if the overpass layer is removed, the MinZoomIndicator still remains when zoomed out.  Older versions had the code ``this._zoomControl._removeLayer(this);`` - possible to reimplement?

Cheers.

**Comment by GuillaumeAmat** [comment]
Of course! And done! ;)
It's available in the new 2.1.2 version.
Thank you for your feedback :)

**Comment by Dr-Mx** [comment]
Don't forget to update your bundle js :)

**Comment by GuillaumeAmat** [comment]
Oh you're right... :P
It's done, thank you.
