### ISSUE TITLE
Make default marker symbol customizable

### ISSUE THREAD

**Issue by wish7code** [GuillaumeAmat/leaflet-overpass-layer#5]
Salut Guillaume,

is the default marker symbol (red dot) somehow customizable? (i.e. use a custom icon instead of the default red dot)

I understand that I could overwrite the onsuccess function  (relevant parts around https://github.com/GuillaumeAmat/leaflet-overpass-layer/blob/master/src/OverPassLayer.js#L51 ), but it makes things more complicated. So I was wondering whether it would make sense to simply make the marker customizable?

Thanks for your great work, sorry if I missed some basic point!

Cheers
Toby

**Comment by GuillaumeAmat** [comment]
Hi @wish7code,

It makes sens of course! I'm running out of time this month so I will take care of that as soon as I got some free time again :)

Thanks for your input!

**Comment by GuillaumeAmat** [comment]
@wish7code I just released the 2.2.0 version which allow to customize the default marker icon :)
You just have to define the `markerIcon` option with a `L.icon` and you're done!
