### ISSUE TITLE
Update Leaflet dependency

### ISSUE THREAD

**Issue by Rudloff** [GuillaumeAmat/leaflet-overpass-layer#7]
Hello,

This plugin still requires Leaflet 0.7 in bower.json although it seems to work correctly with Leaflet 1.0.
Would it be possible to update the depdendency in order to avoid Bower warnings?

**Comment by GuillaumeAmat** [comment]
Hi @Rudloff,

Did you test it for a long time? I will be glad to upgrade the version if you can confirm that there is no problem.

Also, I'm leaving for one week so I will take care of it when I'll be back ;)

**Comment by Rudloff** [comment]
I've been using it on https://openvegemap.netlib.re/ for a few weeks and didn't see any problem.

**Comment by GuillaumeAmat** [comment]
Great! I will upgrade the version as soon as I will be back.
Thanks for your feedback ;)

**Comment by GuillaumeAmat** [comment]
The 2.3.0 is out!
Thanks for your feedback.
