### ISSUE TITLE
Way coordinates are missing

### ISSUE THREAD

**Issue by loviuz** [GuillaumeAmat/leaflet-overpass-layer#73]
Hi, I am using this library and it does seems that if the result of a query is a way (instead of node), I cannot get coordinates. In an example I have found this piece of code:

```javascript
if (e.type === 'node') {
    pos = L.latLng(e.lat, e.lon);
} else {
    pos = L.latLng(e.center.lat, e.center.lon);
}
```
where `e` is the variable that contains the results, but I get the error `e.center is undefined`.

Is there a method to get coordinates of a way?

Thanks in advance

**Comment by trekkete** [comment]
I'm having the exact same issue at the moment.

**Comment by GuillaumeAmat** [comment]
Hey @loviuz @trekkete, sorry for coming back to you this late. I don't have much time to take care of this project, unfortunately.

Your Overpass requests seem to miss the `center` keyword, it is required if you want to fetch `way`s with this plugin.

See: https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide#Geometry_attribute_(center,_center)
