### ISSUE TITLE
License notice

### ISSUE THREAD

**Issue by 2EE58** [GuillaumeAmat/leaflet-overpass-layer#8]
Hey,

I'm trying to make this awsome Leaflet plugin working with GNU LibreJS. Therefore I have to know which licenses are in use. According to the LICENSE file in this repo it uses the MIT license. But the last sentence notes there are other libraries included:

> Please note that this software includes other libraries or parts of libraries which have their own license file or license annotation in the source code and may be released under different licences.

I coudn't find anything else containing another license info.
Are there actually any other libraries included I have to bear in mind when using the files inside the /dist folder?

Thanks guys!

**Comment by GuillaumeAmat** [comment]
Hi @2EE58!
I have updated the LICENSE file with the real MIT license content. That mention is no longer in it.
It was useless.
Thanks for your feedback.
