### ISSUE TITLE
Can't find on npm

### ISSUE THREAD

**Issue by jakehm** [GuillaumeAmat/leaflet-overpass-layer#9]
I can't find the package on npm when I do 'yarn add leaflet-layer-overpass'.  Pretty sure I'm not spelling it wrong so what's up?

Leaflet-overpass-layer did install something.  Is that another package or is your readme wrong?

**Comment by GuillaumeAmat** [comment]
Hi @jakehm,

The correct spelling is *leaflet-overpass-layer*, see here: https://www.npmjs.com/package/leaflet-overpass-layer

So `yarn add leaflet-overpass-layer` should do the work.
